// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.App = (function() {
    App.prototype.appName = "N/A";

    App.prototype.device = null;

    function App($screen) {
      this.$screen = $screen;
      this.onClose = bind(this.onClose, this);
      this.onOpen = bind(this.onOpen, this);
      this.checkCanClose = bind(this.checkCanClose, this);
      this.checkCanOpen = bind(this.checkCanOpen, this);
    }

    App.prototype.checkCanOpen = function() {
      return true;
    };

    App.prototype.checkCanClose = function() {
      return true;
    };

    App.prototype.onOpen = function() {
      return console.log("[APP: " + this.appName + "] onOpen");
    };

    App.prototype.onClose = function() {
      return console.log("[APP: " + this.appName + "] onClose");
    };

    return App;

  })();

}).call(this);

//# sourceMappingURL=app.js.map
