// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.HubDevice = (function() {
    HubDevice.prototype.notificationActive = false;

    function HubDevice($device) {
      this.$device = $device;
      this.notify = bind(this.notify, this);
    }

    HubDevice.prototype.notify = function(active) {
      if (active == null) {
        active = true;
      }
      this.notificationActive = active;
      return console.log("[DEVICE] notify (state = " + state + ") has not been defined on device " + this);
    };

    return HubDevice;

  })();

}).call(this);

//# sourceMappingURL=hubdevice.js.map
