// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Locale = (function() {
    function Locale() {
      this.getLine = bind(this.getLine, this);
      this.buildDialogueLines = bind(this.buildDialogueLines, this);
      this.loadDialogueLines = bind(this.loadDialogueLines, this);
    }

    Locale.prototype.loadDialogueLines = function(dialoguesFilename) {
      return $.getJSON(dialoguesFilename, this.buildDialogueLines).done(function() {
        return console.log("[LOAD] Loaded localized dialogue lines");
      }).fail(function() {
        return console.log("[LOAD] Failed loading localized dialogues");
      });
    };

    Locale.prototype.buildDialogueLines = function(data) {
      return this.dialogueLines = data;
    };

    Locale.prototype.getLine = function(lineID) {
      var line, lineNo, missionID, ref, textNo;
      ref = lineID.split('_'), missionID = ref[0], textNo = ref[1], lineNo = ref[2];
      line = this.dialogueLines[missionID][textNo][lineNo];
      if (line == null) {
        throw new Error("Locale for lineID " + lineID + " not found");
      }
      return line;
    };

    return Locale;

  })();

}).call(this);
