// Generated by CoffeeScript 1.10.0
(function() {
  var main;

  $("document").ready(function() {
    console.log("[DOCUMENT] Ready");
    return main();
  });

  main = function() {
    var dataDeferred, loadHTMLDeferred, storyGraph;
    this.game = new Game("./");
    loadHTMLDeferred = game.loadModules().done(function() {
      return game.initModules();
    });
    dataDeferred = game.loadData("data/dialoguegraphs.json");
    storyGraph = new StoryGraph;
    storyGraph.addNode(new StoryNode("initial", (function() {
      game.playBGM();
      return setTimeout((function() {
        return game.phone.startDialogueByName("mission-tutorial.proposal");
      }), 2000);
    }), ["to-be-continued"]));
    storyGraph.addNode(new StoryNode("to-be-continued"));
    return $.when(loadHTMLDeferred, dataDeferred).done(function() {
      return game.loadLocale(game.settings.lang);
    }).done(function() {
      return game.story.start(storyGraph);
    });
  };

}).call(this);

//# sourceMappingURL=main.js.map
