// Generated by CoffeeScript 1.10.0
(function() {
  var testHub;

  $("document").ready(function() {
    console.log("[TEST] Hub");
    return $.get("../../src/modules/hub.html", function(data) {
      $("#content").html(data);
      console.log("DONE");
      return $.get("../../src/modules/chat.html", function(data) {
        $("#phoneContent").html(data);
        console.log("CHAT DONE");
        return testHub();
      });
    });
  });

  testHub = function() {
    return initHub();
  };

}).call(this);

//# sourceMappingURL=testhub.js.map
