// Generated by CoffeeScript 1.10.0
(function() {
  var testTerminal;

  $(function() {
    console.log("[TEST] Terminal");
    return $("#content").load("../../src/modules/terminal.html", function(response, status, xhr) {
      if (status !== "success") {
        console.log("Loading HTML failed.");
        return;
      }
      console.log("Loaded HTML");
      return testTerminal();
    });
  });

  testTerminal = function() {
    return this.terminal = new Terminal($("#terminal-screen"));
  };

}).call(this);

//# sourceMappingURL=testterminal.js.map
