// Generated by CoffeeScript 1.10.0
(function() {
  var incrementNbModulesAndStartIfReady, testGame;

  $("document").ready(function() {
    console.log("[DOCUMENT] Ready");
    return $.get("../../src/modules/hub.html", function(data) {
      $("#content").html(data);
      console.log("DONE");
      Game.nbReadyModules = 0;
      $.get("../../src/modules/chat.html", function(data) {
        $("#chatContent").html(data);
        console.log("CHAT DONE");
        return incrementNbModulesAndStartIfReady();
      });
      return $.get("../../src/modules/terminal.html", function(data) {
        $("#terminalContent").html(data);
        console.log("TERMINAL DONE");
        return incrementNbModulesAndStartIfReady();
      });
    });
  });

  incrementNbModulesAndStartIfReady = function() {
    ++Game.nbReadyModules;
    if (Game.nbReadyModules === 2) {
      console.log("[MODULES] Ready, start test");
      return testGame();
    }
  };

  testGame = function() {
    var lang, storyGraph;
    lang = "fr";
    this.game = new Game("../../src/");
    game.initModules();
    game.loadData("data/dialoguegraphs.json");
    game.loadLocale("locales/" + lang + "/dialogues.json");
    storyGraph = new StoryGraph;
    storyGraph.addNode(new StoryNode("initial", (function() {
      return game.chat.startDialogueByName("mission-tutorial.proposal");
    }), ["chapter1"]));
    storyGraph.addNode(new StoryNode("chapter1", ["option", "ending"]));
    storyGraph.addNode(new StoryNode("option", ["ending"]));
    storyGraph.addNode(new StoryNode("ending"));
    return setTimeout((function() {
      return game.story.start(storyGraph);
    }), 1500);
  };

}).call(this);

//# sourceMappingURL=testgame.js.map
