// Generated by CoffeeScript 1.10.0
(function() {
  var testChat;

  $("document").ready(function() {
    console.log("[TEST] Chat");
    return $("#content").load("../../src/modules/chat.html", function(response, status, xhr) {
      if (status !== "success") {
        console.log("Loading HTML failed.");
        return;
      }
      console.log("Loaded HTML");
      return testChat(5)();
    });
  });

  testChat = function() {
    var chat;
    chat = new Chat($("#chat-screen"));
    chat.receiveAllMessages(3, 2000);
    return chat.showMessageInputChoiceList();
  };

}).call(this);

//# sourceMappingURL=testchat.js.map
