// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Chat = (function() {
    function Chat() {
      this.displayMessageSequence = bind(this.displayMessageSequence, this);
      this.displayNextMessage = bind(this.displayNextMessage, this);
    }

    Chat.incomingMessageSequence = ["Hi!", "How are you?", "Is everything alright?"];

    Chat.prototype.chatHistoryList = $(".chat-history").find("ul");

    Chat.prototype.nextIncomingMessageIdx = 0;

    Chat.prototype.displayNextMessage = function() {
      var context, template;
      template = Handlebars.compile($("#message-template").html());
      context = {
        messageOutput: Chat.incomingMessageSequence[this.nextIncomingMessageIdx],
        time: "12:00"
      };
      this.chatHistoryList.append(template(context));
      return ++this.nextIncomingMessageIdx;
    };

    Chat.prototype.displayMessageSequence = function(nbMessages, timeInterval) {
      if (nbMessages === 0) {
        return;
      }
      this.displayNextMessage();
      return setTimeout(((function(_this) {
        return function() {
          return _this.displayMessageSequence(nbMessages - 1, timeInterval);
        };
      })(this)), timeInterval);
    };

    return Chat;

  })();

}).call(this);

//# sourceMappingURL=chat.js.map
