// Generated by CoffeeScript 1.10.0
(function() {
  this.Game = {
    events: {
      "player_is_dead": false
    },
    servers: {
      "local": new Server("N/A", "456.231.24.57", ["home"]),
      "google": new Server("google.com", "256.241.23.02", ["etc", "home", "var"], [
        new DatabaseSim([
          new Table("user_table", {
            0: new Google.User(0, "john", "dd6x5few961few68fq4wd6", "California")
          })
        ])
      ])
    },
    dns: {
      "google.com": "256.241.23.02"
    }
  };

}).call(this);

//# sourceMappingURL=game.js.map
