// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var chat;
    console.log("[GAME] Ready");
    chat = new Chat($("#chat-screen"));
    chat.receiveAllMessages(3, 2000);
    return chat.showMessageInputChoiceList();
  });

}).call(this);

//# sourceMappingURL=main.js.map
