// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    console.log("[GAME] Ready");
    return $("#content").load("modules/testchat.html", function(response, status, xhr) {
      var chat;
      if (status === "success") {
        console.log("YES");
        chat = new Chat($("#chat-screen"));
        return console.log(String(chat));
      } else {
        return console.log("NO");
      }
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
