// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var chat;
    console.log("[GAME] Ready");
    chat = new Chat;
    return chat.displayMessageSequence(3, 2000);
  });

}).call(this);

//# sourceMappingURL=main.js.map
