// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Server = (function() {
    function Server(url, ip, databaseList) {
      this.url = url;
      this.ip = ip;
      this.databaseList = databaseList;
    }

    return Server;

  })();

  this.DatabaseSim = (function() {
    function DatabaseSim(tables) {
      this.tables = tables != null ? tables : [];
    }

    return DatabaseSim;

  })();

  this.Table = (function() {
    function Table(rows) {
      this.rows = rows != null ? rows : [];
    }

    return Table;

  })();

  this.Process = (function() {
    function Process() {
      this.execute = bind(this.execute, this);
    }

    Process.prototype.execute = function(terminal) {};

    return Process;

  })();

}).call(this);

//# sourceMappingURL=server.js.map
