// Generated by CoffeeScript 1.10.0
(function() {
  this.Terminal = (function() {
    function Terminal(terminalScreen) {
      5;
    }

    return Terminal;

  })();

}).call(this);

//# sourceMappingURL=terminal.js.map
