// Generated by CoffeeScript 1.10.0
(function() {
  var testChat;

  $("document").ready(function() {
    console.log("[TEST] Chat");
    return $("#content").load("../../src/modules/chat.html", function(response, status, xhr) {
      if (status !== "success") {
        console.log("Loading HTML failed.");
        return;
      }
      console.log("Loaded HTML");
      return testChat();
    });
  });

  testChat = function() {
    var chat, dialogueNode0, dialogueNode1, dialogueNode2;
    chat = new Chat($("#chat-screen"));
    dialogueNode0 = new DialogueNode(0, ["Hi!", "How are you?"], [new DialogueChoice(0, "Fine, thanks.", 1), new DialogueChoice(1, "Not very good today.", 2)]);
    dialogueNode1 = new DialogueNode(1, ["Nice!"], []);
    return dialogueNode2 = new DialogueNode(2, ["Oh, sorry for you."], []);
  };

}).call(this);

//# sourceMappingURL=testchat.js.map
